### ISSUE TITLE
Реализовать отображение реестра

### ISSUE THREAD

**Issue by friendlyted** [Kalinka555/ToyShop#3]
При наличии первого аргумента "list-products" (и только при его наличии) пользователь программы должен иметь возможность получить полный список товаров. Если программа запущена вовсе без параметров, или с параметрами "/?", "-?", "-h", "--help", то надо вывести следующий текст:

```
Usage:
  java -jar ToyShop.jar [command] [options]
Commands:
  list-products            Show all avaliable products in the shop
  /?, -?, -h, --help       Show help and usage information
```

В любом случае, после вывода программа завершается.

**Comment by Alima-T** [comment]
Программа должна выводить полный список товаров при наличии первого аргумента "list-products" - это название аргумента? А второй параметр какой?

**Comment by friendlyted** [comment]
list-products - это первый по счёту аргумент, указанный при запуске программы, примерно так
`C:\Users\Alina\>java -jar ToyShop.jar list-products`

**Comment by friendlyted** [comment]
создай RullRequest для сливания ветки #3  в master и назначь меня его исполнителем.

**Comment by Alima-T** [comment]
А будет оценка какая-нибудь моей работы? Обратная связь? ))

**Comment by friendlyted** [comment]
Обратная связь по коду - в рамках pull request (он же merge request).
Тут отпишу, если будут проблемы при тестировании.

**Comment by Kalinka555** [comment]
Хорошо. Здесь тоже предусмотрены смайлики, значит разрешено быть не слишком серьезными )

**Comment by Kalinka555** [comment]
но я сейчас удалю коммент, чтобы не засорять )

**Comment by friendlyted** [comment]
Похоже, ваша программа работает не полностью ;)
