### ISSUE TITLE
Добавить команду "create-order"

### ISSUE THREAD

**Issue by friendlyted** [Kalinka555/ToyShop#6]
Пользователь ToyShop должен иметь возможность внети информацию о желаемой покупке.

Для этого надо предусмотреть команду "create-order" со следующими опциями:
* артикул (ID) товара
* количество
* адрес доставки

Программа должна сгенерировать случайный номер заказа от 1 до 9999.
Информацию о созданном заказе программа должна сохранить в виде файла в текущей папке (cd), название файла формата order-{order_id}.txt, где {order_id} - это сгенерированный номер заказа.
В ответ на команду программа должна его подтвердить и поблагодарить за заказ.

**Comment by friendlyted** [comment]
Не забудь обновить help новой командой

**Comment by friendlyted** [comment]
Да, и ещё программа должна показать пользователю номер заказа, конечно же.

**Comment by friendlyted** [comment]
Опции - это тоже параметры командной строки, если что (java -jar ToyShop.jar [command] **[options]**).

**Comment by Alima-T** [comment]
Закончила. Закомитила. При добавлении мастера в локальную папку пропали вся работа за последние время, пришлось заново все восстанавливать, хотя я сохранила и закомитила перед этим, оттуда потом и брала информацию, но она несколько искаженная там, некоторых строк не было, где то краказябры. Короче, лучше не удалять матера, наверное, если будет большая работа оч жалко времени будет потом на восстановление.

**Comment by friendlyted** [comment]
Как я уже говорил, лучше сразу создавать ветку, и работать в ней уже. В любом случае, это полезный опыт.

**Comment by friendlyted** [comment]
Для того, чтобы твои изменения могли заехать в основную ветку, надо создавать pull request.

**Comment by friendlyted** [comment]
Идентификаторы в реестре от 1001, а в программе стоит проверка от 100001 до 1000000.

**Comment by friendlyted** [comment]
Укажи в описании команды полный формат: `create-order <id> <count> <deliveryAddress>`.

**Comment by Alima-T** [comment]
pull request выкинул меня на новый комментарий в GitHub, в итоге все равно идет как ответ, да еще #7 присвоился...

**Comment by friendlyted** [comment]
Сейчас, если не указать нужные параметры в команду, напечатаются жуткие ошибки, в результате которых обычному смертному не совсем понятно, что именно пошло не так. Произведи, пожалуйста, тестирование со следующими кейсами:

- не указать ничего, кроме самой команды
- не указать адрес
- указать только номер товара
- указать число (тут не понятно, что это, id или количество) и адрес
- указать все, но номер товара написать буквами
- количество - аналогично буквами

В любом из этих случаев пользователь должен понимать, что именно пошло не так. Не все же с головой окунулись в IT)
